
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install CP4WAIOPS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: TIMESTAMP -              🟢 START - AI MANAGER INSTALLATION
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"



- name: AI Manager -         🚀 Install Custom Resource - INSTALL AI MANAGER
  kubernetes.core.k8s:
    state: present
    template: './templates/waiops/4_waiops-install-template.j2'