
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX (open source Ansible Tower)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX
# --------------------------------------------------------------------------------------------------------------------------------------
# Create AWX

- name: TIMESTAMP -              🟢 START - INSTALL AWX
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


  
- name: AWX -                🚀 Create AWX Operator
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/operator-install.yaml
  
- name: AWX -                🚀 Create AWX Instance
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/awx-deploy-cr.yml
