
- name: TIMESTAMP -              🟢 START - LOAD LOG TRAINING DATA
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: TRAINING LOAD LAD -        🚀 CREATE CLUSTERROLE
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/default-cluserrole.yaml
    

- name: TRAINING LOAD LAD -        🚀 LOAD ELASTICSEARCH LOG DATA 
  kubernetes.core.k8s:
    state: present
    namespace: turbonomic
    src: ./templates/training/load-job-logs.yaml

