
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Connection Details
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Cluster FQDN
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# WAIOPS
# --------------------------------------------------------------------------------------------------------------------------------------
- name: LOGIN -  🚀 WAIOPS
  shell: |
    ../tools/20_get_logins.sh > ../LOGINS.txt
  ignore_errors: yes


# --------------------------------------------------------------------------------------------------------------------------------------
# EventManager
# --------------------------------------------------------------------------------------------------------------------------------------
- name: LOGIN -  🚀 ADDONS - EventManager
  block:
  - name: LOGIN -  🚀 ADDONS - EventManager
    shell: |
      cat ../LOGINS.txt
    ignore_errors: yes

