

- name: TIMESTAMP -              🟢 START - LOAD SNOW TRAINING DATA
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: TRAINING LOAD SNOW -       🚀 CREATE CLUSTERROLE
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/default-cluserrole.yaml
    

- name: TRAINING LOAD SNOW -       🚀 LOAD ELASTICSEARCH SNOW DATA 
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/load-job-snow.yaml
  